### ISSUE TITLE
Bug: Remove Node does not delete itself from parent's child set

### ISSUE THREAD

**Issue by eisenwr** [Primary-Key/Tree-Map-API#4]
When removing a node in the Tree Map, that node is not removed from its parent's child set. This causes phantom tree control & XML entries.
Example of issue in Tree Control example
![2020-02-21_21h40_05](https://user-images.githubusercontent.com/54156730/75085827-bdb81c80-54f2-11ea-814f-f2c393c658ea.png)

**Comment by eisenwr** [comment]
The issue appears to be in Get Parent Path. The returned Parent Path is invalid as it is missing the leading \.
![2020-02-21_21h55_33](https://user-images.githubusercontent.com/54156730/75086010-f822b900-54f4-11ea-8fda-c8bc44536db2.png)

**Comment by SoftwareMinimalist** [comment]
First of all thank you so much for finding this bug. I have committed a modification right now which I think fixes the issue. Can you please confirm it works with all your examples and I will close the issue?

**Comment by eisenwr** [comment]
I can confirm the fix works for both the Tree Control and XML issues I had seen. I have attached my test code, which is just modified version of your examples. Please feel free to use it to test future releases.
[Test Code.zip](https://github.com/Primary-Key/Tree-Map-API/files/4244886/Test.Code.zip)
